language: node_js
node_js:
  - "12.2.0"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: "njOQhvka1Dqr26v7j48vQRfzvhrivA8869glHxrtBhi8P62OJCLY5ugSTOrHNzb3WUI5UXqlTSNJ4UOHPEmZOWk0P8yOqQu5G+NzJCSkCAYWcjnaYUFlJSFDRSuGj4n5yDNSzaeFzUQvF62Aj3Tst5yzrV6t52GmzxtIQBl2Am69/LTMdxIQA2TaJSdxiL7iKQgKe2EwPZDpfm+X6jVaUI3/sSk3LMSVn3D/MySMfE17WsUl/19Q2KzIh/JSo+9C+rKVtujzagqZ4Y6hkzoCOH6NB2lxm5ZDwVRJjd32wEMHGHme3PUt5PVZuFWQrUyFGD29Eft8fdnDCgP8CiVJfcvIoPkO2j7/ORPldmY4ivfhFHcr1jkfMFoPoX+JcNYoicJGWyoGRkx61HdwfQstvXRnDRktkjmQCaTPZZpyDMO7YPMosxQkgXyFjYvLpqSoh1YE8y28Gnu3Ki+7WsG/ynXtHaMsujtxMVomvI0mfTRvMmfrI15BiE4U+y9w8EHeZSbtvT8sGlMXrX7dwKfiIb9gPh0IIuJmuRmoxP333QT66eznHVWWtz08k2wgI6A7B7fTKlAEcG7mJOkvOMhYJGUw4ZO/hH8FtaNn9AZ0HGza9jCHlLdAgyZKUKdBPw9tPhxSq/+suXtyaGNqhrSQbccgspQWOPCQ8QmhSzByTAg="
  secret_access_key:
    secure: "qAqXDvnzF+a0xbqN4/0HgIfGPMZP4N5QyrT3b3e7Li5/zTIT2Tvq+XqIxgV0fgb7N3anZS+IZ+4XwZEcU2Z8KwP8L75CIWknhyfEkSBPH4A5b4jjmjEm8rVMTqgM9i+XqYxluFxUmq7psoCBxha8fYdaBDtziDKO+tkTaCawOVe2wAJzUFFraI+jPZ1XURGdk17aMlrWkBcGblgSfHUE6h9O7KjSW+OPfWlyXtm1dNqFHIArjGdmVbmZMDe7XgXiH/6ejrd5zQaf93C59Le7chQBmIKS1UBc2O5AbTMrZY+P2dgEUWi+SVXOizsOrHKLIj0azQ1o5lPqUttY/H63xQEyXLxuAWJHVtJGBhe4M06xmWFMvNw25eO/0/irkT87t6YyP7a6TFQqqcT4a8cwiHWqfekLjQtcTvrRefEhgbP5jGkIX1Je8+rknDlMmFUBTMyt1j5zhB6+QrGopvB0KgHV1B4XpJiBb5bYiMBPa3MgCLF4r3ITahYIhYTihwoJLTmbowSe615liAxPpEzOiXPYuAwiZENzFfVIMRvBgbzhuV4SfGbkWrfV1mhTWX5MAWVphKosM86rieWkx872XVcLufuPzTKj1z6LKd/LLlXuB3mSZL+rGfDEhy/OoxH9f+GJRCmM1NBYSZuAN2uQUcWnm8isKQ8r9eah7Gec5gk="
  bucket: element84-react-prod
  local_dir: ./build
  region: us-east-1
  on:
    branch: master
  provider: s3
  skip_cleanup: true
  access_key_id:
    secure: "njOQhvka1Dqr26v7j48vQRfzvhrivA8869glHxrtBhi8P62OJCLY5ugSTOrHNzb3WUI5UXqlTSNJ4UOHPEmZOWk0P8yOqQu5G+NzJCSkCAYWcjnaYUFlJSFDRSuGj4n5yDNSzaeFzUQvF62Aj3Tst5yzrV6t52GmzxtIQBl2Am69/LTMdxIQA2TaJSdxiL7iKQgKe2EwPZDpfm+X6jVaUI3/sSk3LMSVn3D/MySMfE17WsUl/19Q2KzIh/JSo+9C+rKVtujzagqZ4Y6hkzoCOH6NB2lxm5ZDwVRJjd32wEMHGHme3PUt5PVZuFWQrUyFGD29Eft8fdnDCgP8CiVJfcvIoPkO2j7/ORPldmY4ivfhFHcr1jkfMFoPoX+JcNYoicJGWyoGRkx61HdwfQstvXRnDRktkjmQCaTPZZpyDMO7YPMosxQkgXyFjYvLpqSoh1YE8y28Gnu3Ki+7WsG/ynXtHaMsujtxMVomvI0mfTRvMmfrI15BiE4U+y9w8EHeZSbtvT8sGlMXrX7dwKfiIb9gPh0IIuJmuRmoxP333QT66eznHVWWtz08k2wgI6A7B7fTKlAEcG7mJOkvOMhYJGUw4ZO/hH8FtaNn9AZ0HGza9jCHlLdAgyZKUKdBPw9tPhxSq/+suXtyaGNqhrSQbccgspQWOPCQ8QmhSzByTAg="
  secret_access_key:
    secure: "qAqXDvnzF+a0xbqN4/0HgIfGPMZP4N5QyrT3b3e7Li5/zTIT2Tvq+XqIxgV0fgb7N3anZS+IZ+4XwZEcU2Z8KwP8L75CIWknhyfEkSBPH4A5b4jjmjEm8rVMTqgM9i+XqYxluFxUmq7psoCBxha8fYdaBDtziDKO+tkTaCawOVe2wAJzUFFraI+jPZ1XURGdk17aMlrWkBcGblgSfHUE6h9O7KjSW+OPfWlyXtm1dNqFHIArjGdmVbmZMDe7XgXiH/6ejrd5zQaf93C59Le7chQBmIKS1UBc2O5AbTMrZY+P2dgEUWi+SVXOizsOrHKLIj0azQ1o5lPqUttY/H63xQEyXLxuAWJHVtJGBhe4M06xmWFMvNw25eO/0/irkT87t6YyP7a6TFQqqcT4a8cwiHWqfekLjQtcTvrRefEhgbP5jGkIX1Je8+rknDlMmFUBTMyt1j5zhB6+QrGopvB0KgHV1B4XpJiBb5bYiMBPa3MgCLF4r3ITahYIhYTihwoJLTmbowSe615liAxPpEzOiXPYuAwiZENzFfVIMRvBgbzhuV4SfGbkWrfV1mhTWX5MAWVphKosM86rieWkx872XVcLufuPzTKj1z6LKd/LLlXuB3mSZL+rGfDEhy/OoxH9f+GJRCmM1NBYSZuAN2uQUcWnm8isKQ8r9eah7Gec5gk="
  bucket: element84-react-test
  local_dir: ./build
  region: us-east-1
  on:
    branch: development
