language: node_js
node_js:
- 12.2.0
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  matrix:
  - provider: s3
    skip_cleanup: true
    access_key_id:
      secure: OuBQVahlKGYaWpTN1drJyRXT0ZCgD18kg/bOP9eqpaUUntIwqlVvG33mgwiK3wdL7wXQzv4MgOs7mVpFxqrgoBlmoJogLK5V3C7fc7AtIXGMmEL40vcAV+D2LkbvAXOTklEl2G3/5Uz2p2d61/XRR5gGTOfgiqxt2+eKesWQ26lY5sZQqsykhMvVT1s7OTdJMg9TbZwSgMFb3yz3L9owXtf0SQgd3VELbvfwFWp2bteEm2Bprq1pNdQYUJTsL4allhkgPukDsGG29D0AmQzMe27irIq51prwJUrGHxSiOKEfpYUhAkbQj5AQZOORqDUEEll98/YQanVpyNhHBmSvJEFV+wORUCXA0g7jVPNcI5c+OJvXchkzbjBKdWpX5+9IUQEJaxHsU5iDVB0iEo764dAfaQw/ouGKKIT/GkuSMixiJhhbr+aGQGTlwGn7Qiace9GI3tdsInwdciSrtx36nlcqQM3wSv/nzXwyxFEl6XR+3wKkGRYQPyV/3cMpUyumRBk8wZS1Jz72NB0Qw2feU/opdaoYGT+n98fvYGFmhWfQORe+1KCBI8c+wJKx/QV/I/nZHksEDp/x5Hs+Dso3pB6BmEXGJHVyDZxvEWYUMNFAI9ym88DZmHCwXuajz69nURbq4Iw/ANRfO5Vpx95eLd925yBPDM4byYlKD8hvX6I=
    secret_access_key:
      secure: OMdQxFhCG++rhSJbVy5+NJutXPYOix5WWmpo2w8OZiJNp54PSf1n40Zp/uJu69BVUAbxWX4Af3Cy9xMAnE3544aDK4sOJqJ4yl9ruY1u7v54AobMZXsXmw50qaErqj0S9UMKK4v6zlf48xykD9XkLyeq6DdwPlYK4LCC3a4/9/dmHtIYjenuL2hrxOAGZpTdWe8uo+K5kYhBQE5/+nP8hp4DS7GswfknBGssTFjAP5O4PBiAPepGDadjJYkWnXZl+kYCLv/5pvUFFVuIj2GGXSalmisnZqNiYM5+OgWlbhZAkBtp8WEEgxoryege8kWRt1ap8X2MZKU4xK1bdoCajYtKn981QwKH1I6+BOpJGIs6YICw4/Lb299309P2Ds0/BI76gI/PPsBAfn3c5NmZls39qE++Sy59XdY8m+Mi2ga6llCpJAOg5tAO0dEYvfk3+/bGMr+4EUYEk6QN1RTnaZIo8XeADr7W4a4aRsGvfumUKaen7LHBD2BmxYQts1hH0VLTiqPp13jlSu/TihdbVQkxwKA2zIlUlwJ4lH1oyPpGE/w3I8yaP4Ej8ZnEFCHV6/cgU0IsbtXuJS0VBx7nzbQ6OtgMeDSTQh3KAJn2RQ55Ux1hzVuHHi7prelH8r60RGipCtn5K0Ml+/f6eyqhnireZ2j+/tso7bHzJlBEpTY=
    bucket: element84-react-prod
    local_dir: "./build"
    region: us-east-1
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id:
      secure: OuBQVahlKGYaWpTN1drJyRXT0ZCgD18kg/bOP9eqpaUUntIwqlVvG33mgwiK3wdL7wXQzv4MgOs7mVpFxqrgoBlmoJogLK5V3C7fc7AtIXGMmEL40vcAV+D2LkbvAXOTklEl2G3/5Uz2p2d61/XRR5gGTOfgiqxt2+eKesWQ26lY5sZQqsykhMvVT1s7OTdJMg9TbZwSgMFb3yz3L9owXtf0SQgd3VELbvfwFWp2bteEm2Bprq1pNdQYUJTsL4allhkgPukDsGG29D0AmQzMe27irIq51prwJUrGHxSiOKEfpYUhAkbQj5AQZOORqDUEEll98/YQanVpyNhHBmSvJEFV+wORUCXA0g7jVPNcI5c+OJvXchkzbjBKdWpX5+9IUQEJaxHsU5iDVB0iEo764dAfaQw/ouGKKIT/GkuSMixiJhhbr+aGQGTlwGn7Qiace9GI3tdsInwdciSrtx36nlcqQM3wSv/nzXwyxFEl6XR+3wKkGRYQPyV/3cMpUyumRBk8wZS1Jz72NB0Qw2feU/opdaoYGT+n98fvYGFmhWfQORe+1KCBI8c+wJKx/QV/I/nZHksEDp/x5Hs+Dso3pB6BmEXGJHVyDZxvEWYUMNFAI9ym88DZmHCwXuajz69nURbq4Iw/ANRfO5Vpx95eLd925yBPDM4byYlKD8hvX6I=
    secret_access_key:
      secure: OMdQxFhCG++rhSJbVy5+NJutXPYOix5WWmpo2w8OZiJNp54PSf1n40Zp/uJu69BVUAbxWX4Af3Cy9xMAnE3544aDK4sOJqJ4yl9ruY1u7v54AobMZXsXmw50qaErqj0S9UMKK4v6zlf48xykD9XkLyeq6DdwPlYK4LCC3a4/9/dmHtIYjenuL2hrxOAGZpTdWe8uo+K5kYhBQE5/+nP8hp4DS7GswfknBGssTFjAP5O4PBiAPepGDadjJYkWnXZl+kYCLv/5pvUFFVuIj2GGXSalmisnZqNiYM5+OgWlbhZAkBtp8WEEgxoryege8kWRt1ap8X2MZKU4xK1bdoCajYtKn981QwKH1I6+BOpJGIs6YICw4/Lb299309P2Ds0/BI76gI/PPsBAfn3c5NmZls39qE++Sy59XdY8m+Mi2ga6llCpJAOg5tAO0dEYvfk3+/bGMr+4EUYEk6QN1RTnaZIo8XeADr7W4a4aRsGvfumUKaen7LHBD2BmxYQts1hH0VLTiqPp13jlSu/TihdbVQkxwKA2zIlUlwJ4lH1oyPpGE/w3I8yaP4Ej8ZnEFCHV6/cgU0IsbtXuJS0VBx7nzbQ6OtgMeDSTQh3KAJn2RQ55Ux1hzVuHHi7prelH8r60RGipCtn5K0Ml+/f6eyqhnireZ2j+/tso7bHzJlBEpTY=
    bucket: element84-react-test
    local_dir: "./build"
    region: us-east-1
    on:
      branch: development
  secret_acccess_key:
    secure: ORUfRChHAJIA5XNLTfFbRS4uRFwGj4TsVIxT3oFscnpOCNxgG6Z5dsgFp7t0+vwcksHbh2FEadiMhumzkhNej1ie0hmVLsnb/9x3stBu+dSYQljB5PXO+fjgO0+tiufISG20E4YPsqmBGHrQi5GaMCLJ01hQp79f22c0pfOwsTK1VqH0DlomWMXzR6N/CYwuiaY2r64tLEia6NfX5JLSlaUSkNOy4jgytSpI4IZimrr2w/69la5rzYUgPrMejqv577KRfEwez7I2HjBOXA+D80Cgm7QTAmb6BGbix0nTIGWz/Rhzw6B8wnMw2ifMEniweY+Gblo6kvQXnmm/FoBWq2DHklKr64mVzNK3y2fuICCB7nsk/1fzNdh8l8o8dTqdoWruRvAiGZk8PG3E/n/g9jNiGXiyIHarQcv0AdkC9jQhQs/c/zFz9qKSmeL5hDPqNSXxOCJW1YXS5My9vx9guQcJ0vHWHea1nhgoXlVGPzikMbGZIgR5SSoi5HRVon/E2KHb6Pvkma8cLGXBramqsOFvnG7fdRbFHa88MnKYSomlYUAMmUn1weuV95EBa9qs7zbwjWxVTL6SAlfiEGQdSaS0IK3DGvGOtMJMEgOAQnmcfMZZpja9QGYxWolwoRCd1pHlcCaGWtJB0ZCDmR62/fCuEanAlSc7nmrA9GUz72A=
