language: node_js
node_js:
- 12.2.0
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  matrix:
  - provider: s3
    skip_cleanup: true
    secret_acccess_key:
      secure: ORUfRChHAJIA5XNLTfFbRS4uRFwGj4TsVIxT3oFscnpOCNxgG6Z5dsgFp7t0+vwcksHbh2FEadiMhumzkhNej1ie0hmVLsnb/9x3stBu+dSYQljB5PXO+fjgO0+tiufISG20E4YPsqmBGHrQi5GaMCLJ01hQp79f22c0pfOwsTK1VqH0DlomWMXzR6N/CYwuiaY2r64tLEia6NfX5JLSlaUSkNOy4jgytSpI4IZimrr2w/69la5rzYUgPrMejqv577KRfEwez7I2HjBOXA+D80Cgm7QTAmb6BGbix0nTIGWz/Rhzw6B8wnMw2ifMEniweY+Gblo6kvQXnmm/FoBWq2DHklKr64mVzNK3y2fuICCB7nsk/1fzNdh8l8o8dTqdoWruRvAiGZk8PG3E/n/g9jNiGXiyIHarQcv0AdkC9jQhQs/c/zFz9qKSmeL5hDPqNSXxOCJW1YXS5My9vx9guQcJ0vHWHea1nhgoXlVGPzikMbGZIgR5SSoi5HRVon/E2KHb6Pvkma8cLGXBramqsOFvnG7fdRbFHa88MnKYSomlYUAMmUn1weuV95EBa9qs7zbwjWxVTL6SAlfiEGQdSaS0IK3DGvGOtMJMEgOAQnmcfMZZpja9QGYxWolwoRCd1pHlcCaGWtJB0ZCDmR62/fCuEanAlSc7nmrA9GUz72A=
    access_key_id:
      secure: X5DM1bsVrAWbVT6PKNBkf99Z+TJGJma3deGMij40phLB2XOuIV7ayvUWfEXQeqZa5ERBnQc+2ouIOQTiXUjZ0/Pfyhwux8rqfU9eClLRGDEB/Pupp4qU73uJOS9Q6757qdY8nRKTXlHWu+dHTlpSDwh20NjArlHEZB7t7f6yKxBhOluQ3cVX0c/PQW8WPEL7ojaNEqiysIlW6nVPcAdph0PbUD5i7zxePSDQEml0xZc5bo8uqtlavkZlmkMEckyk+wj022O5gQfgVRDCbc/lvEHuGjtOXnulCJQsGZ2O542dhOZUTQOWL0wBl/yY/fKvgzDrnT7f11RJbrdw2TbM8V9jDwDHfEZ88F+qPL/fgR0xkFc/wex5iCXUNxEAGvdkBw1FXhhJFYWnv2kfOKxZB6EKKO8gUgR1rxrgBRhUFg9Wia31d8MZzwBWDsLTvaM+8VOJL+BKPYFe5L0jck0dQV24u7pQg5FXXkdA3arW5CUm3nmUfjfMsLW5JVUOxXkK5Cx170YxflntfY9Ax40cC7M3MDPj7ykYXk8T9hUf372KTrzJi3ptC6vPVLSVczTdjiRxqPaEUoIyMMY+5AmEltQFhJrBlCu1JGlsZu3kGHJSFb4lqFeFEPVNZvlvgruncyfwO7oIpfvjuQj/BiE69TEA4HyGDQ1Gbqtxh0ccjzQ=
    bucket: element84-react-prod
    local_dir: "./build"
    region: us-east-1
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    secret_acccess_key:
      secure: ORUfRChHAJIA5XNLTfFbRS4uRFwGj4TsVIxT3oFscnpOCNxgG6Z5dsgFp7t0+vwcksHbh2FEadiMhumzkhNej1ie0hmVLsnb/9x3stBu+dSYQljB5PXO+fjgO0+tiufISG20E4YPsqmBGHrQi5GaMCLJ01hQp79f22c0pfOwsTK1VqH0DlomWMXzR6N/CYwuiaY2r64tLEia6NfX5JLSlaUSkNOy4jgytSpI4IZimrr2w/69la5rzYUgPrMejqv577KRfEwez7I2HjBOXA+D80Cgm7QTAmb6BGbix0nTIGWz/Rhzw6B8wnMw2ifMEniweY+Gblo6kvQXnmm/FoBWq2DHklKr64mVzNK3y2fuICCB7nsk/1fzNdh8l8o8dTqdoWruRvAiGZk8PG3E/n/g9jNiGXiyIHarQcv0AdkC9jQhQs/c/zFz9qKSmeL5hDPqNSXxOCJW1YXS5My9vx9guQcJ0vHWHea1nhgoXlVGPzikMbGZIgR5SSoi5HRVon/E2KHb6Pvkma8cLGXBramqsOFvnG7fdRbFHa88MnKYSomlYUAMmUn1weuV95EBa9qs7zbwjWxVTL6SAlfiEGQdSaS0IK3DGvGOtMJMEgOAQnmcfMZZpja9QGYxWolwoRCd1pHlcCaGWtJB0ZCDmR62/fCuEanAlSc7nmrA9GUz72A=
    access_key_id:
      secure: X5DM1bsVrAWbVT6PKNBkf99Z+TJGJma3deGMij40phLB2XOuIV7ayvUWfEXQeqZa5ERBnQc+2ouIOQTiXUjZ0/Pfyhwux8rqfU9eClLRGDEB/Pupp4qU73uJOS9Q6757qdY8nRKTXlHWu+dHTlpSDwh20NjArlHEZB7t7f6yKxBhOluQ3cVX0c/PQW8WPEL7ojaNEqiysIlW6nVPcAdph0PbUD5i7zxePSDQEml0xZc5bo8uqtlavkZlmkMEckyk+wj022O5gQfgVRDCbc/lvEHuGjtOXnulCJQsGZ2O542dhOZUTQOWL0wBl/yY/fKvgzDrnT7f11RJbrdw2TbM8V9jDwDHfEZ88F+qPL/fgR0xkFc/wex5iCXUNxEAGvdkBw1FXhhJFYWnv2kfOKxZB6EKKO8gUgR1rxrgBRhUFg9Wia31d8MZzwBWDsLTvaM+8VOJL+BKPYFe5L0jck0dQV24u7pQg5FXXkdA3arW5CUm3nmUfjfMsLW5JVUOxXkK5Cx170YxflntfY9Ax40cC7M3MDPj7ykYXk8T9hUf372KTrzJi3ptC6vPVLSVczTdjiRxqPaEUoIyMMY+5AmEltQFhJrBlCu1JGlsZu3kGHJSFb4lqFeFEPVNZvlvgruncyfwO7oIpfvjuQj/BiE69TEA4HyGDQ1Gbqtxh0ccjzQ=
    bucket: element84-react-test
    local_dir: "./build"
    region: us-east-1
    on:
      branch: development
