language: node_js
node_js:
  - "12.2.0"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: SECRET_ACCESS_KEY
  bucket: element84-react-prod
  local_dir: ./build
  region: us-east-1
  on:
    branch: master
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: SECRET_ACCESS_KEY
  bucket: element84-react-test
  local_dir: ./build
  region: us-east-1
  on:
    branch: development
