language: node_js
node_js:
- 12.2.0
cache:
  directories:
  - node_modules
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
befroe_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
script:
- npm test
- npm run build
deploy:
  - provider: script
    script: deploys/deploy_script.sh
    on:
      branch: master
  - provider: script
    script: deploys/deploy_script_dev.sh
    on:
      branch: developoment
