language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  bucket: element84-react-prod
  local_dir: ./build
  region: us-east-1
  on:
    branch: master
  provider: s3
  bucket: element84-react-test
  local_dir: ./build
  region: us-east-1
  on:
    branch: development
