language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  access_key_id:
    secure: "nLIIRbavnsMaRQHr4QzI0+2YSfp74MuCZJIw/AkMuGH1Y1NbvRNhYRl9z1emaF00o2fjDftIdRTmdJDtRfmR2jMJ0KVPa3bbjzvbaJkTzYBa+sUzvIzFZNf8txKy7qBpapsulQG7SuiGW0SObSrnvNPRKrsuKDzBK0J4/Hhcp6xDf4W8gXFxiRsFC1TObEsTxQEy/ZfOtXxY9Znbf0tZKvxDmx6nMEp8BcinBMDPqit6HWodvCC6EoLMdlzB4kOAv3ON10OGD3ZUcLBPDg0zKV50SppVVwWAJOmVrg87Kdeq1eaLJNCxoqjliC9jwIwNE6pndo93vipSf2V06uE+mOSB4KCHF5mPLQrNaLVGLUM3t3OIjKszcGtsOdT8I2qajqZTcq4FsLlmnvfO9n46MQXkPPM1S3mB5dRULyZkk7HE0lAYtfLYzGGL8CuOnNCOJGGfiME9h/4S/SpjLSsVFOkW/8ga431FBG/FWKUKUAERng42ddgc25xsArg36aSQvkigRTY2+DmK0CVGZqho2a58/ckfMkDYKoWF2afVfPgIIT5CN2rrHpaQ+a42+bbLCTeSQkvLW4PEoH59617ZO7bkR82KuhsBnImLMXR89FVevYvKVijOyD9Vp37mdI6FPhjiJdwOfX5f0sTkvd0Syl+K7b8epp2BOWkrfAtQ6O4="
  secret_access_key: "s+jeCn/IUzHAk7X5b6TIZUEcxqixn0aHzigKXo6vBcReXaLWMD/3Q8Y8G7xEK09K0jFxt2LAuoqokgwmK88o5iQXSvMdRLgDVIWAa5UpTE417LXEnyvIoOY4IFjz2HU0k+efk6jx8fC7H8oTU/37s8KsFCp0Ev1rMiaOG3Td0uZbHT9SQyjLGC77oPwTyTNlaKnmkfclKfXFvklsKpzTfjH2iQvYv9xOp74NgXQDvEPWfeE4lR+l38AHWQne98F9SDjMpb2pFFc0JarYLGgbRMJIZUoto8FEArvPvRDKIJtU/4CsUxhsHWgr0BB0z7YP66VK2//3pS/ADX7m7teYVq/xZHf8o/9S65yyOOz+V6rr4+je2rWE+E+Z7dPK2KiP+Y1aYIaEK9F4oN5pjMav59obHqd31dpaDcpMuNdF8eXvEndXMjJJgA+70g3lfrJ7a+7UWF+xvfP3ddn0fZrfHeUW7R0cMIAI2mgwLRXpXC2juACYeWXuDLrjqL+8zN69WjrMsJ+yNZ+gsP+dHfPEsO/Xa+dLulPmzw+c9yGcfKVUJh0/Hl4CkKVwAvLHIpfB3EOhinQVAPkjoTkzUCUn8QhVU78FY4eQMUS7bA0c2SmVzTfZjyACIaCSquniuV9VbifiK5tEiPWxGvpIftkjW1gfejcdqsktDk9Wc8+4x7s="
  provider: s3
  bucket: element84-react-test
  region: us-east-1
  local_dir: .build/
  overwrite: true
  on:
    branch: development
deploy:
  provider: s3
  bucket: element84-react-prod
  region: us-east-1
  local_dir: .build/
  overwrite: true
  on:
    branch: master
